# Generated by Django 4.1.7 on 2023-03-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
