# Generated by Django 4.1.7 on 2023-03-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_description_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
